frame_id: $(arg frame_id)
publish_tf: $(arg publish_tf)
sensor_height: $(arg sensor_height)
max_range: $(arg max_range)
upper_limit: $(arg upper_limit)
lower_limit: $(arg lower_limit)
max_vertical_angle: $(arg max_vertical_angle)
min_vertical_angle: $(arg min_vertical_angle)
max_horizontal_angle: $(arg max_horizontal_angle)
min_horizontal_angle: $(arg min_horizontal_angle)
current_filter_level: $(arg current_filter_level)
ip_address: $(arg ip_address)
calibration_path: $(arg calibration_path)